### ISSUE TITLE
Question: what's the difference between this and the elixir langchain repo?

### ISSUE THREAD

**Issue by lovebes** [jessedrelick/agens#6]
https://github.com/brainlid/langchain

I have no experience in ML but thought I'd ask here - please excuse opening an issue for this; this was created only to ask my question. Thanks!

**Comment by jessedrelick** [comment]
Hello and thanks for the question! At first glance I would say the [Elixir LangChain project](https://github.com/brainlid/langchain) is supposed to follow a lot of the [LangChain](https://www.langchain.com) patterns and includes specific adapters for various LLMs and APIs.

`Agens`, on the other hand, is a little more open-ended and focuses more on the actual coordination rather than specific adapters or integrations. You can plug in any custom `GenServer` or `Nx.Serving`, and use it as part of a `Job`, wrap it with an `Agent`, or use it directly as a `Serving`.

If you are new to ML but familiar with Elixir and OTP you may find Agens easier to get started with. If you already have experience with LangChain it’ll probably be easier to use the Elixir version you mentioned instead.

I’ve recently added a [single-file example](https://github.com/jessedrelick/agens/blob/main/examples/phoenix.exs) that you could try for yourself. It will start a Phoenix LiveView application locally that will demonstrate the basics of Agens and could serve as good starting point.

**Comment by lovebes** [comment]
Awesome! Thank you! Yeah I am looking mostly for a drop in and forget kind of abstraction so I love your effort on this. Elixir LangChain is also really awesome and overall excited the development on this front.

Honestly there's just so much good building blocks, Elixir really feels like low-code for modern web app development with full-on support for AI :) Can't wait to have some time with testing out this repo!

**Comment by lovebes** [comment]
Closing it so as to not introduce clutter in the issues tab :)
